### PR TITLE
Add first 200 lines of potential-bad-01

### PR DESCRIPTION
**Pull request by rmarinho**

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
I also fixed the bad assertion message, expected vs actual were switched: https://github.com/jonathanpeppers/inclusive-code-reviews-ml/commit/57beb57189eb7bf086c308c3348c63fa57c9feea

**Comment by rmarinho** [comment]
Yeah i think that we add some positves with "pain" .. and now the model thinks that is ok. hehe i think we need to add more weight to that sentence

**Comment by jonathanpeppers** [comment]
Maybe manually add a couple more bad "pain" examples, enough for it to pass? You can run `npm test` in the `onnxjs` folder to try it.

**Comment by jonathanpeppers** [comment]
"You are a pain in the behind", lol

**Pull request merged**
