### PR TITLE
[ml.net] update our selected ML algorithm

### PR DESCRIPTION
**Pull request by jonathanpeppers**
I ran:

    .\train.ps1 -seconds 300

Which picked a new algorithm:

    ===============================================Experiment Results=================================================
    ------------------------------------------------------------------------------------------------------------------
    |                                                     Summary                                                    |
    ------------------------------------------------------------------------------------------------------------------
    |ML Task: multiclass-classification                                                                              |
    |Dataset: C:\src\inclusive-code-reviews-ml\comments\classified.csv                                               |
    |Total experiment time : 299.32237729999997 Secs                                                                 |
    |Total number of models explored: 59                                                                             |
    ------------------------------------------------------------------------------------------------------------------

    |                                              Top 5 models explored                                             |
    ------------------------------------------------------------------------------------------------------------------
    |     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     |
    |1    LbfgsLogisticRegressionOva                  0.8957         0.7082       4.9          1                     |
    |2    LbfgsLogisticRegressionOva                  0.8944         0.7165       3.5          2                     |
    |3    LbfgsMaximumEntropyMulti                    0.8939         0.7091       4.4          3                     |
    |4    LbfgsMaximumEntropyMulti                    0.8937         0.7103       5.6          4                     |
    |5    LbfgsMaximumEntropyMulti                    0.8935         0.7135       7.7          5                     |
    ------------------------------------------------------------------------------------------------------------------

I have no idea what a lot of these things mean.

But it seems the accuracy at the end is better than before:

    =============== Cross-validating to get model's accuracy metrics ===============
    *************************************************************************************************************
    *       Metrics for Multi-class Classification model
    *------------------------------------------------------------------------------------------------------------
    *       Average MicroAccuracy:     0.889  - Standard deviation: (.013)  - Confidence Interval 95%: (.013)
    *       Average MacroAccuracy:     0.695  - Standard deviation: (.047)  - Confidence Interval 95%: (.046)
    *       Average LogLoss:           .295  - Standard deviation: (.025)  - Confidence Interval 95%: (.025)
    *       Average LogLossReduction:  .304  - Standard deviation: (.051)  - Confidence Interval 95%: (.05)
    *       Average Class 0 Precision: 0.899  - Standard deviation: (.022)  - Confidence Interval 95%: (.022)
    *       Average Class 1 Precision: 0.749  - Standard deviation: (.117)  - Confidence Interval 95%: (.115)
    *************************************************************************************************************

Class 1 Precision seems like it went up by 4.9%?

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
This change causes test failures:
```
Text 'You are a failure', IsNegative 1, Confidence 0.6959819197654724
Text 'I don't like this.', IsNegative 1, Confidence 0.688410758972168
Text 'Why are you such a pain?', IsNegative 1, Confidence 0.6167618036270142
Text 'I have no faith in this code', IsNegative 0, Confidence 0.5328907370567322
Text 'This code stinks', IsNegative 1, Confidence 0.5366673469543457
Text 'This code really sucks.', IsNegative 1, Confidence 0.5883811116218567
```
Previously, the confidence on all these was higher than 0.7.

Maybe @luisquintanilla can help us look into this? Maybe we need a way to tell the `ml.net` tool how to "score" the algorithm it picks.

**Comment by luisquintanilla** [comment]
cc: @LittleLittleCloud

**Comment by LittleLittleCloud** [comment]
Looks like the training pipeline gets changed, which should be the cause for why confidence (score) decreases. The way how the score is calculated depends on the calibrator and it's not related to the trainer, nor affects the training result if the evaluation metric is Accuracy.

I won't be too worried about it as confidence(score) is not a solid indicator of how well a model is. The 4.9% increasing in accuracy metric, however, is a big jump.

**Comment by jonathanpeppers** [comment]
@LittleLittleCloud the way we use this model, is we underline text in comments if `IsNegative` is 1, with a confidence over 0.7. 

Something like this would hopefully have a confidence of 0.9 or higher:

image

If we used the more accurate model, what would be the confidence we should underline? Is 0.6 a reasonable number?

**Comment by jonathanpeppers** [comment]
Our numbers before the training pipeline changed are:
```
*************************************************************************************************************
*       Metrics for Multi-class Classification model      
*------------------------------------------------------------------------------------------------------------      
*       Average MicroAccuracy:     0.883  - Standard deviation: (.011)  - Confidence Interval 95%: (.011)
*       Average MacroAccuracy:     0.713  - Standard deviation: (.031)  - Confidence Interval 95%: (.031)
*       Average LogLoss:           .391  - Standard deviation: (.043)  - Confidence Interval 95%: (.042)
*       Average LogLossReduction:  .077  - Standard deviation: (.087)  - Confidence Interval 95%: (.085)
*       Average Class 0 Precision: 0.879  - Standard deviation: (.083)  - Confidence Interval 95%: (.081)
*       Average Class 1 Precision: 0.695  - Standard deviation: (.116)  - Confidence Interval 95%: (.113)
************************************************************************************************************* 
```

**Comment by jonathanpeppers** [comment]
Closing in favor of https://github.com/jonathanpeppers/inclusive-code-reviews-ml/pull/62

I had better success when I tried this again -- our training dataset size also doubled.

**Pull request closed without merging**
